### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by heylf** [JesperGrud/IMAGE#2]
Dear Jesper,
Your tool is very handy and more sophisticated than other approaches. I would like to integrate your tool in Galaxy, because a lot of other people could benefit from it. For this purpose I would create a conda package for your tool, with your consent. 

Your tool hast not an open source license that is why I need to ask. 

Best wishes,
Florian

**Comment by JesperGrud** [comment]
Dear Florian,

I'm really happy to hear you want to put IMAGE on Galaxy. You have my consent and please, let me know if you need any help.

Best regards, 
Jesper
