### ISSUE TITLE
Error in Analyzing gene expression

### ISSUE THREAD

**Issue by gcIL20** [JesperGrud/IMAGE#4]
Hi, I am just trying out IMAGE on the example data provided, but I run into an issue with the R script. 

My input is as suggested in the README.txt:

`IMAGE.pl -region IMAGE/examples/Enhancers.txt -expression IMAGE/examples/GeneExpression.txt -fasta GRCm39.primary_assembly.genome.fa.gz -RNADesign 1 1 2 2 3 3 4 4 -EnhancerDesign 1 1 2 2 3 3 4 4 -p 2 -n Test`

The output:
Starting the analysis
        Setting up for parallizing motif search
        Preparing input file for motif searching
        Scanning for motifs
        Running analysis in R
                1. Reading data into R
                2. Analyzing gene expression
Error in names(x) <- value :
  'names' attribute [1] must be the same length as the vector [0]
Calls: colnames<- -> colnames<-
Execution halted
                3. Converting motif hits to matrix - Takes a whileError in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection

Anything I can do to solve this?

**Comment by JesperGrud** [comment]
Hi.

Did you run IMAGE using the conda environment specified in the environment.txt file in the release?

Best,
Jesper

**Comment by gcIL20** [comment]
Not seeing any environment.txt anywhere. Can you provide a link, please?

**Comment by gcIL20** [comment]
> Not seeing any environment.txt anywhere. Can you provide a link, please?

I found this evnvironment.txt file, but still have the same issue running the conda env.

**Comment by seoltj10** [comment]
Hi, it seems that using GENCODE primary assembly fasta file (I used `GRCm38.primary_assembly.genome.fa`) can reproduce the same error as @gcIL20. 
However, when I used `mm10.fa` from UCSC, It executed successfully without any errors.

**Comment by cfuttner** [comment]
I'm having the same issue, however mm10.fa does not resolve. Any other solutions?

**Comment by gcIL20** [comment]
> I'm having the same issue, however mm10.fa does not resolve. Any other solutions?

Using mm10.fa (making sure to unzip first) fixed the issue for me.

**Comment by JesperGrud** [comment]
The issue seems resolved I'm closing the issue.
